import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("API_KEY")
SECRET_KEY = os.getenv("SECRET_KEY")
ALPACA_PAPER = os.getenv("ALPACA_PAPER", "true").lower() == "true"

DOLLARS_PER_TRADE = 25
MAX_POSITIONS = 5
MAX_TOTAL_CAPITAL = 130
ETF_ONLY_MODE = True

HARD_STOP_PERCENT = 0.08
# Backward-compatible name used by older integrations.
STOP_LOSS_PERCENT = HARD_STOP_PERCENT
ATR_WINDOW = 14
ATR_TRAILING_MULTIPLIER = 2.0
PULLBACK_LOOKBACK = 10
PULLBACK_EMA_TOLERANCE = 0.01
PULLBACK_SMA_TOLERANCE = 0.02

MA_SHORT = 50
MA_LONG = 200

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

MARKET_REGIME_SYMBOL = "SPY"
MARKET_REGIME_MA_SHORT = 50
MARKET_REGIME_MA_LONG = 200

MIN_CANDIDATE_SCORE = None
MAX_NEW_BUYS_PER_CYCLE = 2
MAX_BUYS_PER_CYCLE = MAX_NEW_BUYS_PER_CYCLE
BLOCKED_SYMBOLS = []

ENABLE_MARKET_REGIME_FILTER = True
ENABLE_MA_ALIGNMENT_FILTER = True
ENABLE_MACD_FILTER = True
ENABLE_RELATIVE_STRENGTH_SCORE = True
ENABLE_RELATIVE_STRENGTH_FILTER = ENABLE_RELATIVE_STRENGTH_SCORE
ENABLE_MOMENTUM_SCORE = True
ENABLE_VOLUME_FILTER = False
ENABLE_ATR_TREND_FILTER = False
ENABLE_MIN_SCORE_FILTER = MIN_CANDIDATE_SCORE is not None
ENABLE_TOP_CANDIDATE_SELECTION = True
ENABLE_BULLISH_CANDLE_CONFIRMATION = False
ENABLE_DYNAMIC_MIDPOINT_STOP = True
ENABLE_ATR_STOP = False
ENABLE_ATR_TRAILING_STOP = ENABLE_ATR_STOP
ENABLE_EMA_EXIT = False
ENABLE_MACD_EXIT = False
ENABLE_FIXED_STOP_LOSS = True

SCAN_INTERVAL_SECONDS = 300
MAX_CANDIDATES_PER_CYCLE = 10
