import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("API_KEY")
SECRET_KEY = os.getenv("SECRET_KEY")
ALPACA_PAPER = os.getenv("PAPER_API_KEY", "true").lower() == "true"

DOLLARS_PER_TRADE = 15
MAX_POSITIONS = 8
MAX_TOTAL_CAPITAL = 120

STOP_LOSS_PERCENT = 0.05
ATR_WINDOW = 14
ATR_TRAILING_MULTIPLIER = 2.0

MA_SHORT = 50
MA_LONG = 200

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

MARKET_REGIME_SYMBOL = "SPY"
MARKET_REGIME_MA_SHORT = 50
MARKET_REGIME_MA_LONG = 200

MIN_CANDIDATE_SCORE = 1.5
MAX_BUYS_PER_CYCLE = 2
BLOCKED_SYMBOLS = ["XLY"]

ENABLE_MARKET_REGIME_FILTER = True
ENABLE_MA_ALIGNMENT_FILTER = True
ENABLE_MACD_FILTER = True
ENABLE_RELATIVE_STRENGTH_FILTER = True
ENABLE_VOLUME_FILTER = True
ENABLE_ATR_TREND_FILTER = True
ENABLE_MIN_SCORE_FILTER = True
ENABLE_TOP_CANDIDATE_SELECTION = True
ENABLE_ATR_TRAILING_STOP = True
ENABLE_FIXED_STOP_LOSS = True

SCAN_INTERVAL_SECONDS = 300
MAX_CANDIDATES_PER_CYCLE = 10
