CORE_ETFS = [
    "SPY", "QQQ", "DIA", "IWM"
]

SECTOR_ETFS = [
    "XLK", "XLF", "XLE", "XLV", "XLI",
    "XLY", "XLP", "XLU", "XLB", "XLRE", "XLC"
]

OPTIONAL_ETFS = [
    "SMH", "SOXX", "VGT", "VOO", "SCHD", "IYW", "IYT"
]

MEGA_CAPS = [
    "AAPL", "MSFT", "NVDA", "AMZN", "META",
    "GOOGL", "AVGO", "TSLA", "AMD", "NFLX"
]

LARGE_CAP_LEADERS = [
    "JPM", "UNH", "COST", "WMT", "HD",
    "CAT", "LLY", "JNJ", "XOM", "CVX"
]

ETF_UNIVERSE = CORE_ETFS + SECTOR_ETFS + OPTIONAL_ETFS
STOCK_UNIVERSE = MEGA_CAPS + LARGE_CAP_LEADERS
COMBINED_UNIVERSE = ETF_UNIVERSE + STOCK_UNIVERSE

UNIVERSE = ETF_UNIVERSE
